-- Seed all remaining prompt library data
-- This migration adds prompts for: Dangerfield, Bar, Basic, Halloween, Selfie, Victoria

-- Modern Day Dangerfield prompts (99 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('dangerfield', 'I get no respect. Even my phone auto-corrects me to ___.', 1),
  ('dangerfield', 'My dating bio just says I look like I ___.', 2),
  ('dangerfield', 'My smart fridge sent me a notification telling me to stop ___.', 3),
  ('dangerfield', 'My therapist said I need better coping skills, so now I just ___.', 4),
  ('dangerfield', 'I finally saved money! Then I spent it all on ___.', 5),
  ('dangerfield', 'I matched with someone great. They only liked me for my ___.', 6),
  ('dangerfield', 'I tried a meditation app. It told me I''m too stressed for ___.', 7),
  ('dangerfield', 'My anxiety told me to act normal, so I ___.', 8),
  ('dangerfield', 'My landlord raised rent because they caught me ___.', 9),
  ('dangerfield', 'I get no respect. Even my coffee order called me ___.', 10),
  ('dangerfield', 'I asked AI how to improve my life. It recommended ___.', 11),
  ('dangerfield', 'My therapist''s Zoom froze right when I admitted ___.', 12),
  ('dangerfield', 'I bought insurance, but it only covers ___.', 13),
  ('dangerfield', 'My date said they want someone ''emotionally available,'' so I told them ___.', 14),
  ('dangerfield', 'I tried self-care and ended up ___.', 15),
  ('dangerfield', 'HR said I need better communication, so I sent them ___.', 16),
  ('dangerfield', 'I asked for a raise. They offered me exposure and ___.', 17),
  ('dangerfield', 'I finally did positive affirmations. They all said ___.', 18),
  ('dangerfield', 'My barista asked if I''m okay because I ___.', 19),
  ('dangerfield', 'My coping mechanism is just ___.', 20),
  ('dangerfield', 'My bank account sends me reminders to stop ___.', 21),
  ('dangerfield', 'My side hustle is so sad, I make money by ___.', 22),
  ('dangerfield', 'I ordered a latte with almond milk. They served me ___.', 23),
  ('dangerfield', 'Matcha doesn''t calm me. It just makes me ___.', 24),
  ('dangerfield', 'My company gave us mental health benefits — they let us ___.', 25),
  ('dangerfield', 'My doctor diagnosed me with ___.', 26),
  ('dangerfield', 'I tried doing yoga. The instructor told me to start with ___.', 27),
  ('dangerfield', 'My scale looked at me and said ___.', 28),
  ('dangerfield', 'At the gym, the trainer told me to try ___.', 29),
  ('dangerfield', 'My parents said they''re proud of me for finally ___.', 30),
  ('dangerfield', 'Even my playlist skipped my favorite song for ___.', 31),
  ('dangerfield', 'I met someone great. First thing they said was, "You look like someone who ___.', 32),
  ('dangerfield', 'My date said they love confidence, so I impressed them by ___.', 33),
  ('dangerfield', 'They ghosted me politely with a message saying ___.', 34),
  ('dangerfield', 'We finally kissed, and they whispered ___.', 35),
  ('dangerfield', 'I asked a financial advisor for help. They said my best investment is ___.', 36),
  ('dangerfield', 'My student loans sent a thank you card for ___.', 37),
  ('dangerfield', 'I bought a wellness drink. It promised to cure ___.', 38),
  ('dangerfield', 'My boss said I''m ''on thin ice'' just for ___.', 39),
  ('dangerfield', 'I dressed for the job I want, so I showed up as ___.', 40),
  ('dangerfield', 'My coworkers call me MVP — Most ___ Person.', 41),
  ('dangerfield', 'Even Santa didn''t like me. He brought me ___.', 42),
  ('dangerfield', 'As a kid, even my toys bullied me. My teddy bear called me ___.', 43),
  ('dangerfield', 'They said I''d grow up to ___.', 44),
  ('dangerfield', 'My teacher said I was gifted, just not in ___.', 45),
  ('dangerfield', 'My performance review said I ''lack initiative'' because I kept ___.', 46),
  ('dangerfield', 'This bar is so cheap, even the bartender tipped ___.', 47),
  ('dangerfield', 'The drink hit me so hard I started confessing about ___.', 48),
  ('dangerfield', 'The bartender cut me off after I tried to ___.', 49),
  ('dangerfield', 'I said I needed a strong drink. They recommended ___.', 50),
  ('dangerfield', 'My bank app congratulated me for ___.', 51),
  ('dangerfield', 'I bought a smart scale. It said ___.', 52),
  ('dangerfield', 'My headphones disconnected just as I started ___.', 53),
  ('dangerfield', 'Even my group chat kicked me out for ___.', 54),
  ('dangerfield', 'My therapist said I''m afraid of commitment — even my ___ left me.', 55),
  ('dangerfield', 'I tried manifestation. All I manifested was ___.', 56),
  ('dangerfield', 'I tried journaling, but I only wrote about ___.', 57),
  ('dangerfield', 'Even my anxiety has anxiety about ___.', 58),
  ('dangerfield', 'My coping mechanism costs $12 and tastes like ___.', 59),
  ('dangerfield', 'My friends said I need hobbies, so I started ___.', 60),
  ('dangerfield', 'I get no respect. Even my houseplants judge me for ___.', 61),
  ('dangerfield', 'I tried crystals for healing. They told me to work on ___.', 62),
  ('dangerfield', 'My horoscope said today is perfect for ___.', 63),
  ('dangerfield', 'I started budgeting, and now all I can afford is ___.', 64),
  ('dangerfield', 'My bank account said I should try ___.', 65),
  ('dangerfield', 'My date said they like mysterious people. They meant someone who ___.', 66),
  ('dangerfield', 'My crush said I have potential, but only if I stop ___.', 67),
  ('dangerfield', 'They matched with me because they thought I looked like I like ___.', 68),
  ('dangerfield', 'My parents said I could be anything. So I became ___.', 69),
  ('dangerfield', 'My therapy homework was just to stop ___.', 70),
  ('dangerfield', 'Even the bar''s DJ roasted me by playing ___.', 71),
  ('dangerfield', 'I went clubbing and realized I''m too old when I started ___.', 72),
  ('dangerfield', 'I went clubbing and realized I''m too young when I started ___.', 73),
  ('dangerfield', 'My boss tried to motivate me with a sticker that says ___.', 74),
  ('dangerfield', 'I tried being productive, but I ended up ___.', 75),
  ('dangerfield', 'My alarm clock wakes me up just to remind me I''ll spend the day ___.', 76),
  ('dangerfield', 'I tried intermittent fasting. The only thing I lost was ___.', 77),
  ('dangerfield', 'My smart watch told me to calm down after it detected ___.', 78),
  ('dangerfield', 'I tried positive thinking, but my brain kept saying ___.', 79),
  ('dangerfield', 'I went on a juice cleanse and hallucinated ___.', 80),
  ('dangerfield', 'My date said they want someone stable, so I showed them ___.', 81),
  ('dangerfield', 'I get no respect. Even my TikTok comments called me ___.', 82),
  ('dangerfield', 'My selfie looked so bad even the filter said ___.', 83),
  ('dangerfield', 'I get no respect. My Uber driver told me to stop ___.', 84),
  ('dangerfield', 'Even my cat acts like it pays rent by ___!', 85),
  ('dangerfield', 'I switched to decaf and immediately started ___.', 86),
  ('dangerfield', 'I bought a weighted blanket. It crushed me for ___.', 87),
  ('dangerfield', 'My sleep app said I woke up 17 times because of ___.', 88),
  ('dangerfield', 'I asked for relationship advice, and they recommended ___.', 89),
  ('dangerfield', 'I finally meditated… and all I thought about was ___.', 90),
  ('dangerfield', 'My phone battery lasts longer than my ___.', 91),
  ('dangerfield', 'I joined a gym, and they offered me a class in ___.', 92),
  ('dangerfield', 'Even my shadow left because it got tired of ___.', 93),
  ('dangerfield', 'I tried being spontaneous, so I ___.', 94),
  ('dangerfield', 'I asked ChatGPT for life advice, and it told me to ___.', 95),
  ('dangerfield', 'I tried fixing my life, but the update requires ___.', 96),
  ('dangerfield', 'I tried being delulu, but all I got was ___.', 97),
  ('dangerfield', 'My coping playlist only has songs about ___.', 98);

-- Bar Banter prompts (30 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('bar', 'What''s your signature bar drink?', 1),
  ('bar', 'What''s the weirdest thing you''ve ordered at a bar?', 2),
  ('bar', 'If you could create a new bar game, what would it be?', 3),
  ('bar', 'What''s your go-to karaoke song?', 4),
  ('bar', 'What''s the craziest bar story you have?', 5),
  ('bar', 'If bars served food from other countries, what would you order?', 6),
  ('bar', 'What''s your favorite drinking game?', 7),
  ('bar', 'If you owned a bar, what would be the house special?', 8),
  ('bar', 'What''s the worst bartender experience you''ve had?', 9),
  ('bar', 'If you could time travel to any bar in history, where would you go?', 10),
  ('bar', 'What''s your pre-game ritual?', 11),
  ('bar', 'If you could rename any drink, what would you call it?', 12),
  ('bar', 'What''s the most ridiculous bar bet you''ve made?', 13),
  ('bar', 'If bars had themes, what would be your ideal theme?', 14),
  ('bar', 'What''s your hangover cure?', 15),
  ('bar', 'If you could talk to your younger self at a bar, what would you say?', 16),
  ('bar', 'What''s the best bar snack you''ve ever had?', 17),
  ('bar', 'If you were a cocktail, what would you be?', 18),
  ('bar', 'What''s your bar trivia strength?', 19),
  ('bar', 'If you could ban one drink from all bars, what would it be?', 20),
  ('bar', 'What''s your favorite bar memory?', 21),
  ('bar', 'If bars served breakfast, what would you order?', 22),
  ('bar', 'What''s the most interesting person you''ve met at a bar?', 23),
  ('bar', 'If you could have any superpower at a bar, what would it be?', 24),
  ('bar', 'What''s your bar etiquette pet peeve?', 25),
  ('bar', 'If you were designing bar coasters, what would they say?', 26),
  ('bar', 'What''s the best pickup line you''ve heard at a bar?', 27),
  ('bar', 'If bars had loyalty programs, what would be the ultimate reward?', 28),
  ('bar', 'What''s your favorite bar atmosphere?', 29),
  ('bar', 'If you could teleport to any bar right now, where would you go?', 30);

-- Basic Prompts (30 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('basic', 'What''s something you''re looking forward to?', 1),
  ('basic', 'What''s your favorite way to spend a weekend?', 2),
  ('basic', 'If you could have any job for a day, what would it be?', 3),
  ('basic', 'What''s the best book you''ve read recently?', 4),
  ('basic', 'If you could travel anywhere right now, where would you go?', 5),
  ('basic', 'What''s your favorite type of music?', 6),
  ('basic', 'If you could learn any skill instantly, what would it be?', 7),
  ('basic', 'What''s your go-to comfort food?', 8),
  ('basic', 'If you could meet any historical figure, who would it be?', 9),
  ('basic', 'What''s something that always makes you laugh?', 10),
  ('basic', 'If you could have dinner with any celebrity, who would it be?', 11),
  ('basic', 'What''s your favorite season and why?', 12),
  ('basic', 'If you could change one thing about the world, what would it be?', 13),
  ('basic', 'What''s your favorite hobby?', 14),
  ('basic', 'If you could live in any time period, when would it be?', 15),
  ('basic', 'What''s something you''re really good at?', 16),
  ('basic', 'If you could have any pet, what would it be?', 17),
  ('basic', 'What''s your favorite movie genre?', 18),
  ('basic', 'If you could invent something, what would it be?', 19),
  ('basic', 'What''s something that inspires you?', 20),
  ('basic', 'If you could speak any language fluently, which would it be?', 21),
  ('basic', 'What''s your favorite way to relax?', 22),
  ('basic', 'If you could be any age forever, what age would you choose?', 23),
  ('basic', 'What''s something you''re proud of?', 24),
  ('basic', 'If you could have any superpower, what would it be?', 25),
  ('basic', 'What''s your favorite type of weather?', 26),
  ('basic', 'If you could visit any fictional world, where would you go?', 27),
  ('basic', 'What''s something you collect?', 28),
  ('basic', 'If you could be famous for one thing, what would it be?', 29),
  ('basic', 'What''s your favorite childhood memory?', 30);

-- Halloween prompts (30 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('halloween', 'What''s your scariest Halloween costume idea?', 1),
  ('halloween', 'If you were a ghost, what would haunt?', 2),
  ('halloween', 'What''s the creepiest thing you''ve ever eaten?', 3),
  ('halloween', 'If you could be any monster, what would you be?', 4),
  ('halloween', 'What''s your favorite horror movie?', 5),
  ('halloween', 'If vampires were real, what would you ask them?', 6),
  ('halloween', 'What''s the weirdest pumpkin carving you''ve seen?', 7),
  ('halloween', 'If you could time travel to a haunted house, when would you go?', 8),
  ('halloween', 'What''s your go-to Halloween candy?', 9),
  ('halloween', 'If you were cursed, what would the curse be?', 10),
  ('halloween', 'What''s the most supernatural experience you''ve had?', 11),
  ('halloween', 'If you could summon any spirit, who would it be?', 12),
  ('halloween', 'What''s your favorite Halloween tradition?', 13),
  ('halloween', 'If zombies took over, what would you do?', 14),
  ('halloween', 'What''s the spookiest place you''ve ever been?', 15),
  ('halloween', 'If you could have any magical power on Halloween, what would it be?', 16),
  ('halloween', 'What''s your worst trick-or-treat memory?', 17),
  ('halloween', 'If you were a witch, what would your potion do?', 18),
  ('halloween', 'What''s the most terrifying dream you''ve had?', 19),
  ('halloween', 'If you could visit any haunted location, where would you go?', 20),
  ('halloween', 'What''s your Halloween costume this year?', 21),
  ('halloween', 'If you were invisible for a night, what would you do?', 22),
  ('halloween', 'What''s the creepiest urban legend you''ve heard?', 23),
  ('halloween', 'If you could talk to animals on Halloween, what would they say?', 24),
  ('halloween', 'What''s your favorite spooky story?', 25),
  ('halloween', 'If you were a werewolf, what would your transformation be like?', 26),
  ('halloween', 'What''s the most unusual Halloween decoration you''ve seen?', 27),
  ('halloween', 'If you could predict the future, what would you ask?', 28),
  ('halloween', 'What''s your Halloween party game idea?', 29),
  ('halloween', 'If you could be any mythical creature, what would you choose?', 30);

-- Selfie prompts (30 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('selfie', 'What''s your most creative selfie pose?', 1),
  ('selfie', 'If you could take a selfie with any animal, what would it be?', 2),
  ('selfie', 'What''s the weirdest location you''ve taken a selfie in?', 3),
  ('selfie', 'If selfies could talk, what would yours say?', 4),
  ('selfie', 'What''s your favorite filter?', 5),
  ('selfie', 'If you could time travel for a selfie, when would you go?', 6),
  ('selfie', 'What''s the most embarrassing selfie you''ve taken?', 7),
  ('selfie', 'If you were a selfie expert, what would your advice be?', 8),
  ('selfie', 'What''s your go-to selfie lighting?', 9),
  ('selfie', 'If you could photoshop yourself as anything, what would it be?', 10),
  ('selfie', 'What''s the best selfie you''ve ever taken?', 11),
  ('selfie', 'If you could have any celebrity take your photo, who would it be?', 12),
  ('selfie', 'What''s your selfie style?', 13),
  ('selfie', 'If selfies had personalities, what would yours be?', 14),
  ('selfie', 'What''s the most challenging selfie you''ve attempted?', 15),
  ('selfie', 'If you could only take one type of selfie forever, what would it be?', 16),
  ('selfie', 'What''s your favorite selfie app feature?', 17),
  ('selfie', 'If you were directing a selfie photoshoot, what would the theme be?', 18),
  ('selfie', 'What''s the silliest selfie face you make?', 19),
  ('selfie', 'If you could be in any famous painting as a selfie, which one?', 20),
  ('selfie', 'What''s your selfie background game?', 21),
  ('selfie', 'If you could have any superpower in a selfie, what would it be?', 22),
  ('selfie', 'What''s the most unexpected compliment you''ve gotten on a selfie?', 23),
  ('selfie', 'If selfies could grant wishes, what would yours be?', 24),
  ('selfie', 'What''s your ultimate selfie goal?', 25),
  ('selfie', 'If you could collaborate on a selfie with any artist, who would it be?', 26),
  ('selfie', 'What''s your favorite selfie memory?', 27),
  ('selfie', 'If you were a selfie influencer, what would your brand be?', 28),
  ('selfie', 'What''s the most creative prop you''ve used in a selfie?', 29),
  ('selfie', 'If you could live in a selfie forever, what would it look like?', 30);

-- Victoria Nights prompts (30 prompts)
INSERT INTO prompts (library_id, text, sort_order) VALUES
  ('victoria', 'What''s your favorite spot in Victoria for people watching?', 1),
  ('victoria', 'If you could teleport anywhere in Victoria, where would you go?', 2),
  ('victoria', 'What''s the best local food truck experience you''ve had?', 3),
  ('victoria', 'If Victoria had a superhero, what would their power be?', 4),
  ('victoria', 'What''s your go-to coffee shop in Victoria?', 5),
  ('victoria', 'If you could preserve one Victoria landmark forever, which would it be?', 6),
  ('victoria', 'What''s the most Victoria thing you''ve ever done?', 7),
  ('victoria', 'If you were mayor of Victoria for a day, what would you change?', 8),
  ('victoria', 'What''s your favorite Victoria festival?', 9),
  ('victoria', 'If Victoria''s weather could be anything, what would you choose?', 10),
  ('victoria', 'What''s the best view in Victoria?', 11),
  ('victoria', 'If you could have dinner at any Victoria restaurant, where would it be?', 12),
  ('victoria', 'What''s your Victoria hiking trail recommendation?', 13),
  ('victoria', 'If Victoria had a theme song, what would it be?', 14),
  ('victoria', 'What''s the most surprising thing you''ve learned about Victoria?', 15),
  ('victoria', 'If you could time travel to Victoria''s past, when would you go?', 16),
  ('victoria', 'What''s your favorite Victoria bookstore or library?', 17),
  ('victoria', 'If Victoria hosted the Olympics, what sport would we excel at?', 18),
  ('victoria', 'What''s the best local craft beer you''ve tried?', 19),
  ('victoria', 'If you could rename Victoria, what would you call it?', 20),
  ('victoria', 'What''s your Victoria beach day routine?', 21),
  ('victoria', 'If Victoria''s animals could talk, what would they say about us?', 22),
  ('victoria', 'What''s the most beautiful garden in Victoria?', 23),
  ('victoria', 'If you could add one attraction to Victoria, what would it be?', 24),
  ('victoria', 'What''s your favorite Victoria pub or bar?', 25),
  ('victoria', 'If Victoria had a signature cocktail, what would it be?', 26),
  ('victoria', 'What''s the best local art gallery or museum experience?', 27),
  ('victoria', 'If you could live in any Victoria neighborhood, which would it be?', 28),
  ('victoria', 'What''s your Victoria farmers market find?', 29),
  ('victoria', 'If Victoria were a person, what would their personality be like?', 30);
